# Site settings
title: EK Keramik 
email: evakobel7@gmail.com
description: "Håndlavet keramik af Eva Kobel, Fyn. Skåle, kander, tallerkner og skulpturer i enkle former og klare farver. Køb i butikken, på markeder eller tilmeld dig keramikkursus."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ekkeramik.dk" # the base hostname & protocol for your site

# User setting
owner: EK Keramik - Eva Kobel
email: evakobel7@gmail.com
facebook_username: eva.kobel.3
#twitter_username:
#github_username:
address:
  - line: Torupvej 7, Sandager
  - line: 5610 Assens
  # Feel free to add more lines here 
telephone: +45 2946 7904
cvr: 41035625
mobilepay: 782046
copyright: Copyright (c) 2026 Eva Kobel. All rights reserved.

# Collections
collections:
  sections:
    output: false

# Build settings
markdown: kramdown
