[workspace]
authors = ["Carl M. Kobel <cmkobel@mbg.au.dk>"]
channels = ["conda-forge"]
name = "ekkeramik"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
install = "gem install jekyll"
serve = "jekyll serve"
build = "jekyll build"

[dependencies]
ruby = ">=3.0"
c-compiler = "*"
cxx-compiler = "*"
make = "*"
