[workspace]
authors = ["Carl M. Kobel <cmkobel@mbg.au.dk>"]
channels = ["conda-forge"]
name = "ekkeramik"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
install = "gem install jekyll"
build = "jekyll build"
serve = "jekyll serve"

[dependencies]
ruby = ">=3.0"
c-compiler = "*"
cxx-compiler = "*"
make = "*"
imagemagick = ">=7.1.2_16,<8"
